theme: jekyll-theme-minimal
title: Logan St. Pierre 
description: This is the person website of Notre Dame Computer Science Student Logan St. Pierre. This site contains relevent information concerning him.
